title: My Github Trip
author: Katrina
email: yuqiaohu@andrew.cmu.edu
description: > # this means to ignore newlines until "baseurl:"
  Hi this is really an **exciting** thing!
  I will try to know more about writing blogs.

# social links
twitter_username: secret # DO NOT include the @ character, or else the build will fail!
github_username:  Katrina0406 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
